//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Threads.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Threads.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: \&quot;{0}\&quot;.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is currently in use, please, close programs, that can use it.
        /// </summary>
        internal static string File_Is_Currently_In_Use {
            get {
                return ResourceManager.GetString("File_Is_Currently_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you have no rights to write to selected file. Program will stop writting xml to it.
        /// </summary>
        internal static string Have_No_Write_Permissions {
            get {
                return ResourceManager.GetString("Have_No_Write_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation_Time.
        /// </summary>
        internal static string Service_Creation_Time {
            get {
                return ResourceManager.GetString("Service_Creation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        internal static string Service_Entries {
            get {
                return ResourceManager.GetString("Service_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entry.
        /// </summary>
        internal static string Service_entry {
            get {
                return ResourceManager.GetString("Service_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full_Name.
        /// </summary>
        internal static string Service_FullName {
            get {
                return ResourceManager.GetString("Service_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last_Data_Access_Time.
        /// </summary>
        internal static string Service_Last_Data_Access_Time {
            get {
                return ResourceManager.GetString("Service_Last_Data_Access_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write xml to the file.
        /// </summary>
        internal static string Services_CannotWriteToTheFile {
            get {
                return ResourceManager.GetString("Services_CannotWriteToTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification_Time.
        /// </summary>
        internal static string Services_Modification_Time {
            get {
                return ResourceManager.GetString("Services_Modification_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Services_Owner {
            get {
                return ResourceManager.GetString("Services_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Services_Size {
            get {
                return ResourceManager.GetString("Services_Size", resourceCulture);
            }
        }
    }
}
