//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Threads.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Threads.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denided.
        /// </summary>
        internal static string Access_Denided {
            get {
                return ResourceManager.GetString("Access_Denided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denided for {0}.
        /// </summary>
        internal static string Access_denided_For {
            get {
                return ResourceManager.GetString("Access_denided_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: \&quot;{0}\&quot;.
        /// </summary>
        internal static string Error_message {
            get {
                return ResourceManager.GetString("Error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denided for {0}.
        /// </summary>
        internal static string MainForm_AccessDenided {
            get {
                return ResourceManager.GetString("MainForm_AccessDenided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} doesn&apos;t exist.
        /// </summary>
        internal static string MainForm_DirectoryDoes_not_exsist {
            get {
                return ResourceManager.GetString("MainForm_DirectoryDoes_not_exsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to scan.
        /// </summary>
        internal static string MainForm_FolderBrowserDialog_Description_Select_folder_to_scan {
            get {
                return ResourceManager.GetString("MainForm_FolderBrowserDialog_Description_Select_folder_to_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select file and folder.
        /// </summary>
        internal static string MainForm_StartClick_Please__select_file_and_folder {
            get {
                return ResourceManager.GetString("MainForm_StartClick_Please__select_file_and_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.xml.
        /// </summary>
        internal static string MainForm_Text_file_extension {
            get {
                return ResourceManager.GetString("MainForm_Text_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string MainForm_TextFilesExtension {
            get {
                return ResourceManager.GetString("MainForm_TextFilesExtension", resourceCulture);
            }
        }
    }
}
